:imagesdir: doc/img
= Store microservice application

The store application is an application which consists of 3 microservices along with their corresponding databases and a sso service, for the authentication and authorization.

image::infrastructure.svg["Store service infrastructure"]

== Setup

This project requires the following tools to be available on your machine.

* Java 17
* Maven 3.x.x
* quarkus-cli
* Docker/Docker-Compose
* An IDE of your choice

== Run the store

=== Generate certificates/truststore

Execute the command `./generate-service-certificates.sh` in the project root directory to generate the certificates.

IMPORTANT: The `application.properties` files of the applications don't need to be updated, they are already properly configured.

=== Start the depending service

Execute `docker-compose -f infrastructure/compose up -d` to start the database and sso services.

=== Start the application services

Start the application services each one in a own shell with the command `quarkus dev --debug-port 500x`

== Services

The following sections describe the services the store-microservices-application contains.

=== store-service

The store-service is a Quarkus based application which proivdes the UI (Quarkus Qute) for the store application. The UI is secured via OpenIDConnect but not the welcome page which is public.

The store can be accessed:

* `Standalone` +
https://localhost:8443/api/

=== order-service

The order-service is a Quarkus based application which handles orders for the store. The service is secured and accepts only JWT tokens with the audience `store-service`, so only users logged into the store can access their placed/fullfiles orders and can place new orders.

The order service exposes a swagger-ui which is also secured via OpenIdConnect. To use it, you need to log in with a user and provide the store client_id and client_credential.

The order service api can be tested via:

* `Standalone Swagger-UI` +
https://localhost:8444/q/swagger-ui/

=== warehouse-service

The warehouse-service is a Quarkus based application which handles the available products for the store. The store-service loads available products and the order-service pulls products when a order gets fullfiled. The service is secured and accepts only JWT tokens with the audience `store-service`, so only users logged into the store can access the available products.

The warehouse service exposes a swagger-ui which is also secured via OpenIdConnect. To use it, you need to log in with a user and provide the store client_id and client_credential.

The warehouse service api can be tested via:

* `Standalone Swagger-UI` +
https://localhost:8445/q/swagger-ui/

=== sso-service

The sso-service is Keycloak which handles the authentication/authorization of users.

Available users:

* Keycloak admin +
  keycloak/keycloak
* Store Customer +
  customer/customer

The sso service admin console can be accessed via:

* `Standalone` +
http://localhost:9080/

== Technical Notes

=== Keycloak

When the realm is exported via the GUI then no users are exported so export the full realm via the following command which has to be executed in the directory `/opt/keycloak`

.Export realm 
[source,bash]
----
bin/kc.sh export --realm store --dir data/export
----

This will export the realm and users in teh project directory `infrastructure/compose/keycloak/export`.

The realm and user export need to be merge, because only the realm is imported during startup and therefore we would miss the users.
