{
 "title": "Services Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "System Load ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Threads daemon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Threads live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}