{
 "title": "Store Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pages viewed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(page) (page_viewed_total)",
     "legendFormat": "{{page}}"
    }
   ]
  },
  {
   "title": "Page errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(page) (page_error_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client) (client_error_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders placed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(user) (orders_placed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orders fulfilled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "order_fulfilled_total", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Orders canceled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(user) (orders_canceled_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}