version: '3.1'

services:
  store-db:
    image: postgres:bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
      POSTGRES_DB: store
  order-db:
    image: postgres:bullseye
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
      POSTGRES_DB: order
  warehouse-db:
    image: postgres:bullseye
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
  sso-db:
    image: postgres:bullseye
    restart: always
    environment:
      POSTGRES_USER: sso
      POSTGRES_PASSWORD: sso
      POSTGRES_DB: sso
  sso:
    image: quay.io/keycloak/keycloak:19.0.2
    ports:
      - 9080:8080
      - 9443:8443
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://sso-db:5432/sso
      KC_DB_USERNAME: sso
      KC_DB_PASSWORD: sso
      CLIENT_SECRET_STORE: client-secret-store
      CLIENT_SECRET_ORDER: client-secret-order
      CLIENT_SECRET_WAREHOUSE: client-secret-warehouse
    command: ["start-dev", "--import-realm", "--http-enabled", "false", "--https-key-store-file", "/secret/sso.p12", "--https-key-store-password", "${KEY_STORE_PASSWORD}", "--https-trust-store-file", "/secret/truststore.p12", "--https-trust-store-password", "${TRUST_STORE_PASSWORD}"]
    volumes:
      - ../keycloak/import:/opt/keycloak/data/import:ro
      - ../../secrets/sso.p12:/secret/sso.p12:ro
      - ../../secrets/truststore.p12:/secret/truststore.p12:ro
      - ./keycloak/export:/opt/keycloak/data/export:rw
    depends_on:
      - sso-db
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.38
    ports:
      - "16686:16686"
      - "14250:14250"
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
    depends_on:
      - jaeger