apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{NAME}-db-pvc'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{NAME}-db'
spec:
  replicas: 1
  selector:
    matchLabels:
      service: '{NAME}-db'
  template:
    metadata:
      labels:
        service: '{NAME}-db'
    spec:
      containers:
      - name: '{NAME}-db'
        image: postgres:14-alpine
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        volumeMounts:
        - name: postgres-volume-mount
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          value: '{NAME}'
        - name: POSTGRES_DB
          value: '{NAME}'
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: '{NAME}'
              key: db.password
      restartPolicy: Always
      volumes:
      - name: postgres-volume-mount
        persistentVolumeClaim:
          claimName: '{NAME}-db-pvc'
---
apiVersion: v1
kind: Service
metadata:
  name: '{NAME}-db'
  labels:
    service: '{NAME}-db'
spec:
  selector:
    service: '{NAME}-db'
  type: ClusterIP
  ports:
    - port: 5432